name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      # Only push Docker image on push to master, not during pull requests
      - name: Build & push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: mr-smithers-excellent/docker-build-push@v7
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/springboot-github-cicd-actions
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
